## joins

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [3]:
import pandas as pd

## we can create dataframes using list,dictionary and file

In [4]:
dict1 = {"name":"mani","age":10,"place":"kurnool"}
df2 = pd.DataFrame([dict1])
print(df2)

   name  age    place
0  mani   10  kurnool

In [5]:
dict1 = {"name":["mani","sai"],
         "age":[10,20],
         "place":["kurnool","sai nagar"]}
df2 = pd.DataFrame(dict1)
(df2)

   name  age      place
0  mani   10    kurnool
1   sai   20  sai nagar

In [6]:
dict1 = {"name":["mani","sai","Srav"],
         "age":[10,20,30],
         "place":["kurnool","sai nagar","Madanapalli"]}
df2 = pd.DataFrame(dict1)
(df2)

   name  age        place
0  mani   10      kurnool
1   sai   20    sai nagar
2  Srav   30  Madanapalli

In [7]:
#aggregate funtion is used to aggregate using one or more operator

In [8]:
import pandas as pd

In [9]:
patient_df = pd.read_excel('patientData.xlxs')
patient_df

FileNotFoundError: [Errno 2] No such file or directory: 'patientData.xlxs'

In [ ]:
sorting_patient_df=patient_df.sort_values(by=['Score','Age'],ascending=False)
sorting_patient_df

In [ ]:
!pip install openpyxl
patient_df = pd.read_excel('patientData.xlsx')
patient_df

In [ ]:
## sorting the colums

In [ ]:
patient_df['Age'].sort_values()

In [ ]:
patient_df['Age'].sort_values(ascending=False)

In [ ]:
df['Age'].min()

In [ ]:
patient_df['Age'].min()

In [ ]:
df['Age'].min()

In [ ]:
patient_df = pd.read_excel('patientData_xlxs')
patient_df

In [ ]:
student_df=pd.read_excel('student_records.xlxs')
student_df

## fetch all students whose score is greater than 50 and less than 80

In [ ]:
True and False

In [ ]:
4 and 5

In [ ]:
4 and 0

In [ ]:
4 & 3

In [ ]:
5&7

In [ ]:
student_records_with_nan=pd.read_excel('student_records.xlsx')
student_df

In [ ]:
student_df=pd.read_excel('student_records_with_nan.xlsx')
student_df

In [ ]:
student_records_with_nan.dropna(how='all')

In [ ]:
student_df.dropna(axis=1)

In [ ]:
student_df.dropna(subset=['Name','Age'])

In [ ]:
student_df.dropna(subset=['Name',inplace=True])

In [ ]:
filled_data={
    'Age':student_df['Age'].mean(),
    'Place':student_df['Place'].mode(),
    'Score':student_df['Score'].mean(),
}
filled_data

In [ ]:
student_df.fillna(filled_data,inplace=True)
student_df

In [ ]:
student_df['Age']=student_df['Age'].astype(int)

In [ ]:
#replace_dict = {"Grade":{"A":"A-Grade",
                         "B":"B-Grade",
                         "C":"C-Grade",
                         "D ":"D-Grade",}}

In [21]:
dict = {"name":["mani","sai","Srav"],
         "age":[10,20,30],
         "place":["kurnool","sai nagar","Madanapalli"]}
dict= pd.DataFrame(dict)
(dict)

   name  age        place
0  mani   10      kurnool
1   sai   20    sai nagar
2  Srav   30  Madanapalli

In [20]:
dict2 = {"name":["cherry","lav","jaya"],
         "age":[20,30,30],
         "place":["america","banglore","tirupathi"]}
dict2= pd.DataFrame(dict2)
(dict2)

     name  age      place
0  cherry   20    america
1     lav   30   banglore
2    jaya   30  tirupathi

In [22]:
df=pd.concat([dict,dict2],axis=1)
df

   name  age        place    name  age      place
0  mani   10      kurnool  cherry   20    america
1   sai   20    sai nagar     lav   30   banglore
2  Srav   30  Madanapalli    jaya   30  tirupathi

In [28]:
data1={"id":[1,2,3,4,5],
       "name":["ramesh","suresh","vignesh","raju","venu"]}
data2={"id":[4,5,6,7,8],
       "place":["hyd","kerala","chennai","tirupathi","banglore"]}
df3=pd.DataFrame(data1)
df4=pd.DataFrame(data2)
df3

   id     name
0   1   ramesh
1   2   suresh
2   3  vignesh
3   4     raju
4   5     venu

In [31]:
e1={"emp id":[1,2,3,4,5,6],
    "name":["ramesh","suresh","vignesh","raju","venu","ganesh"]}
d1={"emp id":[4,5,6,7,8,9],
    "dept":["HR","IT","IT","Finance","Finance","HR"]}
e_df=pd.DataFrame(e1)
d_df=pd.DataFrame(d1)

In [33]:
d_df

   emp id     dept
0       4       HR
1       5       IT
2       6       IT
3       7  Finance
4       8  Finance
5       9       HR

In [32]:
pd.merge(e1_df,d_df,left_on="emp

_IncompleteInputError: incomplete input (2872132199.py, line 1)